version: "2.0"
services:
    enb:
        build: srsLTE
        depends_on:
            - epc
        privileged: true
        volumes:
            - /dev/bus/usb:/dev/bus/usb
        networks:
            net1:
                ipv4_address: 192.188.2.253
    epc:
        build:
            context: srsLTE
            dockerfile: Dockerfile.epc
        privileged: true
        networks:
            net1:
                ipv4_address: 192.188.2.2
networks:
    net1:
        ipam:
            driver: default
            config:
                - subnet: 192.188.2.0/24
